---
kind: pipeline
#type: kubernetes
name: default

platform:
  os: linux
  arch: arm64

clone:
  depth: 0

steps:
# abc
- name: docker
  image: plugins/docker
  privileged: true
  settings:
    username:
      from_secret: dockerhub_user
    password:
      from_secret: dockerhub_password
    repo: sando/docker-eturnal
    tags: latest-test
    dry_run: true
    dockerfile: docker-k8s/image/Dockerfile
