---
kind: pipeline
type: kubernetes
name: default

clone:
  depth: 0

steps:
# abc
- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: dockerhub_user
    password:
      from_secret: dockerhub_password
    repo: sando/docker-eturnal
    tags: latest-test
    dry_run: true
    context: docker-k8s/image/.
