apiVersion: apps/v1
kind: Deployment
metadata:
  name: eturnal
  labels:
    app: eturnal
spec:
  selector:
    matchLabels:
      app: eturnal
  template:
    metadata:
      labels:
        app: eturnal
    spec:
      subdomain: eturnal
      initContainers:
        - name: eturnal-config
          image: alpine
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 9000
            runAsGroup: 9000
            runAsNonRoot: true
            privileged: false
            capabilities:
              drop: [ALL]
          command:
            - sh
            - -c
            - |
              cp /configmap/eturnal.yml /config
              chmod -R 600 /config/eturnal.yml
              chown 9000:9000 /config/eturnal.yml
          volumeMounts:
            - name: eturnal-config-modified
              mountPath: /config
            - name: eturnal-config
              mountPath: /configmap/eturnal.yml
              subPath: eturnal.yml
      containers:
        - name: eturnal
          volumeMounts:
          - name: eturnal-config-modified
            mountPath: /opt/eturnal/etc/eturnal.yml
            subPath: eturnal.yml
  #          readOnly: true
      volumes:
        - name: eturnal-config-modified
          emptyDir:
            medium: Memory
        - name: eturnal-config
          configMap:
            name: eturnal-config
