apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nameofsecret
  namespace: stunturn
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
    rotationPolicy: Always
  secretName: nameofsecret
  dnsNames:
  - 'stun.example.com'
  - 'turn.example.com'
