eturnal:
  #secret: "long-and-cryptic"     # Shared secret, CHANGE THIS.
  #relay_ipv4_addr: "10.20.30.40" # The server's public IPv4 address.
  #relay_ipv6_addr: "::"          # The server's public IPv6 address (optional).
  listen:
    -
      ip: "::"
      port: 3478
      transport: udp
    -
      ip: "::"
      port: 3478
      transport: tcp
#    -
#      ip: "::"
#      port: 5349
#      transport: auto
### listener for tls via port 443 via traefik IngressRouteTCP with proxyProtocol (see example)
#    -
#      ip: "::"
#      port: 5350
#      transport: auto
#      proxy_protocol: true
#  tls_crt_file: /opt/eturnal/tls/crt.pem
#  tls_key_file: /opt/eturnal/tls/key.pem
  relay_min_port: 49152     # This is the default.
  relay_max_port: 65535     # This is the default.
  blacklist:                # This is the default blacklist.
    - "127.0.0.0/8"         # IPv4 loopback.
    - "::1"                 # IPv6 loopback.
#    - "10.42.0.0/8"
#    - "10.43.0.0/8"
  strict_expiry: false      # This is the default.
  log_level: info           # critical | error | warning | notice | info | debug
  log_rotate_size: 10485760 # 10 MiB (default: unlimited, i.e., no rotation).
  log_rotate_count: 10      # Keep 10 rotated log files.
  log_dir: stdout           # Enable for logging to the terminal/journal.
  modules:
    mod_log_stun: {}        # Log STUN queries (in addition to TURN sessions).
