# eturnal STUN/TURN server configuration file.
#
# This file is written in YAML. The YAML format is indentation-sensitive, please
# MAKE SURE YOU INDENT CORRECTLY.

eturnal:

  ## ---------------------------------------------------------------------- ##
  ## To enable TURN support, specify a 'secret' and 'relay_ipv4_addr', and  ##
  ## remove the 'enable_turn: false' lines in the 'listen' section below.   ##
  ## ---------------------------------------------------------------------- ##

  ## Shared secret for deriving temporary TURN credentials (MUST be specified):
  #secret: "long-and-cryptic"

  ## The server's public IPv4 address (default: address of $(hostname --fqdn)):
  #relay_ipv4_addr: "203.0.113.4"
  ## The server's public IPv6 address (optional):
  #relay_ipv6_addr: "2001:db8::4"

  listen:
    -
      ip: "::"
      port: 3478
      transport: udp
      enable_turn: false
    -
      ip: "::"
      port: 3478
      transport: tcp
      enable_turn: false
    #-
    #  ip: "::"
    #  port: 5349
    #  transport: tls

  ## TLS certificate/key files (must be readable by 'eturnal' user!):
  #tls_crt_file: /etc/eturnal/tls/crt.pem
  #tls_key_file: /etc/eturnal/tls/key.pem

  ## UDP relay port range (usually, several ports per A/V call are required):
  relay_min_port: 49152     # This is the default.
  relay_max_port: 65535     # This is the default.

  ## Reject TURN relaying from/to these addresses/networks:
  blacklist:                # This is the default blacklist.
    - "127.0.0.0/8"         # IPv4 loopback.
    - "::1"                 # IPv6 loopback.
    - "2001::/32"           # Teredo.
    - "2002::/16"           # 6to4.

  ## Logging configuration:
  log_level: info           # critical | error | warning | notice | info | debug
  log_rotate_size: 10485760 # 10 MiB (default: unlimited, i.e., no rotation).
  log_rotate_count: 10      # Keep 10 rotated log files.
  #log_dir: stdout          # Enable for logging to the terminal/journal.

  ## Module configuration:
  modules:
    mod_log_stun: {}        # Log STUN queries (in addition to TURN sessions).
