{
 "title": "eturnal STUN/TURN server official dashboard",
 "description": "Monitoring eturnal STUN/TURN service activities. This dashboard uses the 'mod_stats_prometheus' with Prometheus as a data source. More info about eturnal can be found in the web: 'eturnal.net'.",
 "tags": [
  "STUN",
  "TURN",
  "eturnal"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "unit",
    "label": "Target server",
    "query": {
     "query": "query_result(eturnal_stun_requests_total)"
    }
   },
   { "name": "threshold_size", "label": "Threshold size [in bytes]", "query": "4096, 32768, 262144" }
  ]
 },
 "panels": [
  {
   "title": "Overall system information, errors & peak rates/load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (unit)(irate(node_cpu_seconds_total{mode=\"system\",unit=\"$unit\",job=\"eturnal.turn\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (unit)(irate(node_cpu_seconds_total{mode='user',unit=\"$unit\",job=\"eturnal.turn\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (unit)(irate(node_cpu_seconds_total{mode='iowait',unit=\"$unit\",job=\"eturnal.turn\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (unit)(irate(node_cpu_seconds_total{mode=~\".*irq\",unit=\"$unit\",job=\"eturnal.turn\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',unit=\"$unit\",job=\"eturnal.turn\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',unit=\"$unit\",job=\"eturnal.turn\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{unit=\"$unit\",job=\"eturnal.turn\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{unit=\"$unit\",job=\"eturnal.turn\"}[5m])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Allocated memory by $unit eturnal",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "erlang_vm_memory_bytes_total{unit=~\"$unit\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{unit=\"$unit\",job=\"eturnal.turn\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{unit=\"$unit\",job=\"eturnal.turn\"} - node_memory_MemFree_bytes{unit=\"$unit\",job=\"eturnal.turn\"} - (node_memory_Cached_bytes{unit=\"$unit\",job=\"eturnal.turn\"} + node_memory_Buffers_bytes{unit=\"$unit\",job=\"eturnal.turn\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{unit=\"$unit\",job=\"eturnal.turn\"} + node_memory_Buffers_bytes{unit=\"$unit\",job=\"eturnal.turn\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{unit=\"$unit\",job=\"eturnal.turn\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{unit=\"$unit\",job=\"eturnal.turn\"} - node_memory_SwapFree_bytes{unit=\"$unit\",job=\"eturnal.turn\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Protocol errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum without (transport) (increase(eturnal_protocol_error_total{unit=~\"$unit\"}[$__rate_interval]))>0",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Current STUN queries, TURN sessions & rates/load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "STUN queries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "irate(sum(eturnal_stun_requests_total{unit=~\"$unit\"}[$__rate_interval]))*$__interval",
     "legendFormat": "STUN queries"
    }
   ]
  },
  {
   "title": "Open TURN sessions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "eturnal_turn_open_sessions{unit=~\"$unit\"}",
     "legendFormat": "{{transport}}"
    }
   ]
  },
  {
   "title": "Transport",
   "type": "stat",
   "description": "*w/o sessions <=$threshold_size bytes ($transport)",
   "gridPos": { "h": 12, "w": 2, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum without (unit,job) (eturnal_turn_relay_rcvd_bytes_sum{unit=~\"$unit\"})) / (sum without (unit,job) ( (eturnal_turn_sessions_total{unit=~\"$unit\"}) - ignoring(le) eturnal_turn_relay_rcvd_bytes_bucket{unit=~\"$unit\",le=~\"$threshold_size\"} ))",
     "legendFormat": "{{transport}}"
    },
    {
     "expr": "(sum without (unit,job,transport) (eturnal_turn_relay_rcvd_bytes_sum{unit=~\"$unit\"})) / (sum without (unit,job,transport) ( (eturnal_turn_sessions_total{unit=~\"$unit\"}) - ignoring(le) eturnal_turn_relay_rcvd_bytes_bucket{unit=~\"$unit\",le=~\"$threshold_size\"} ))",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "↓ Mean* received",
   "type": "stat",
   "description": "*w/o sessions <=$threshold_size bytes ($transport)",
   "gridPos": { "h": 12, "w": 2, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum without (unit,job) (eturnal_turn_relay_rcvd_bytes_sum{unit=~\"$unit\"})) / (sum without (unit,job) ( (eturnal_turn_sessions_total{unit=~\"$unit\"}) - ignoring(le) eturnal_turn_relay_rcvd_bytes_bucket{unit=~\"$unit\",le=~\"$threshold_size\"} ))",
     "legendFormat": "{{transport}}"
    },
    {
     "expr": "(sum without (unit,job,transport) (eturnal_turn_relay_rcvd_bytes_sum{unit=~\"$unit\"})) / (sum without (unit,job,transport) ( (eturnal_turn_sessions_total{unit=~\"$unit\"}) - ignoring(le) eturnal_turn_relay_rcvd_bytes_bucket{unit=~\"$unit\",le=~\"$threshold_size\"} ))",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "↑ Mean* sent",
   "type": "stat",
   "description": "*w/o sessions <=$threshold_size bytes ($transport)",
   "gridPos": { "h": 12, "w": 2, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum without (unit,job) (eturnal_turn_relay_sent_bytes_sum{unit=~\"$unit\"})) / (sum without (unit,job) ( (eturnal_turn_sessions_total{unit=~\"$unit\"}) - ignoring(le) eturnal_turn_relay_sent_bytes_bucket{unit=~\"$unit\",le=~\"$threshold_size\"} ))",
     "legendFormat": "{{transport}}"
    },
    {
     "expr": "(sum without (unit,job,transport) (eturnal_turn_relay_sent_bytes_sum{unit=~\"$unit\"})) / (sum without (unit,job,transport) ( (eturnal_turn_sessions_total{unit=~\"$unit\"}) - ignoring(le) eturnal_turn_relay_sent_bytes_bucket{unit=~\"$unit\",le=~\"$threshold_size\"} ))",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Mean duration [in hh:mm:ss]",
   "type": "stat",
   "gridPos": { "h": 12, "w": 2, "x": 22, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum without (unit,job) (eturnal_turn_session_duration_seconds_sum{unit=~\"$unit\"})) / (sum without (unit,job) ( (eturnal_turn_sessions_total{unit=~\"$unit\"})))",
     "legendFormat": "{{transport}}"
    },
    {
     "expr": "(sum without (unit,job,transport) (eturnal_turn_session_duration_seconds_sum{unit=~\"$unit\"})) / (sum without (unit,job,transport) ( (eturnal_turn_sessions_total{unit=~\"$unit\"})))",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "newly opened TURN Sessions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "irate(sum(eturnal_turn_sessions_total{unit=~\"$unit\"}[$__rate_interval]))*$__interval",
     "legendFormat": "newly opened TURN Sessions"
    }
   ]
  },
  {
   "title": "Open active* TURN sessions",
   "type": "stat",
   "description": "*w/o sessions <=$threshold_size bytes (calculated from past rates)",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "( 1 - \n\n  ( sum without (le,unit,job) ( (eturnal_turn_relay_rcvd_bytes_bucket{unit=~\"$unit\",le=~\"$threshold_size\"} + eturnal_turn_relay_sent_bytes_bucket{unit=~\"$unit\",le=~\"$threshold_size\"}) / 2 ) \n  / ( sum without (le,unit,job) (eturnal_turn_sessions_total{unit=~\"$unit\"}) ) ) )\n\n* ( sum without (le,unit,job) (eturnal_turn_open_sessions{unit=~\"$unit\"}) )",
     "legendFormat": "{{transport}}"
    }
   ]
  },
  {
   "title": "Open inactive* TURN sessions",
   "type": "stat",
   "description": "*only sessions <=$threshold_size bytes (calculated from past rates)",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "( sum without (le,unit,job) ( (eturnal_turn_relay_rcvd_bytes_bucket{unit=~\"$unit\",le=~\"$threshold_size\"} + eturnal_turn_relay_sent_bytes_bucket{unit=~\"$unit\",le=~\"$threshold_size\"}) / 2 ) \n/ ( sum without (le,unit,job) (eturnal_turn_sessions_total{unit=~\"$unit\"}) ) )\n\n* ( sum without (le,unit,job) (eturnal_turn_open_sessions{unit=~\"$unit\"}) )",
     "legendFormat": "{{transport}}"
    }
   ]
  },
  { "title": "Information per TURN session", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Relay data distribution (rcvd↓)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum without (job,unit,transport) ( (irate(eturnal_turn_relay_rcvd_bytes_bucket{unit=~\"$unit\"}[$__rate_interval]))*$__interval)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relay data distribution (sent↑)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "sum without (job,unit,transport) ((irate(eturnal_turn_relay_sent_bytes_bucket{unit=~\"$unit\"}[$__rate_interval]))*$__interval)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Session duration distribution",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "sum without (job,unit,transport) (irate(eturnal_turn_session_duration_seconds_bucket{unit=~\"$unit\"}[$__rate_interval]))*15",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}