#!/bin/sh

# Print the current version string.

set -e
set -u

export PATH='/usr/local/bin:/usr/bin:/bin'

rel_vsn='1.2.1'

( git describe --tags --match '[0-9]*' 2>'/dev/null' || echo "$rel_vsn" ) \
    | sed -e 's/-g.*//' -e 's/-/+/' | tr -d '[:space:]'
