#!/bin/sh

# Print the current version string.

set -e
set -u

rel_vsn='1.10.0'

( git describe --tags --match '[0-9]*' 2>'/dev/null' || echo "$rel_vsn" ) \
    | sed -e 's/-g.*//' -e 's/-/+/' | tr -d '[:space:]'
