#!/bin/sh

# Build portable binary release tarballs for Linux/x64 and Linux/arm64.

set -e
set -u

export PATH='/usr/local/bin:/usr/bin:/bin'

myself=${0##*/}

info()
{
	echo "$myself: $*"
}

error()
{
	echo >&2 "$myself: $*"
}

usage()
{
	echo >&2 "Usage: $myself"
	exit 2
}

if ! [ -e 'rebar.config' ] || ! [ -e "scripts/$myself" ]
then
	error "Please call this script from the repository's root directory."
	exit 2
elif [ $# -ne 0 ]
then
	usage
fi

rel_name='eturnal'
rel_vsn=$(scripts/get-version)
rebar_vsn='3.19.0'
crosstool_vsn='1.25.0'
termcap_vsn='1.3.1'
zlib_vsn='1.2.12'
yaml_vsn='0.2.5'
ssl_vsn='1.1.1q'
otp_vsn='25.0.1'
root_dir="${BUILD_DIR:-/build}"
bootstrap_dir="$root_dir/bootstrap"
ct_prefix_dir="$root_dir/x-tools"
build_dir="$root_dir/$rel_name"
crosstool_dir="crosstool-ng-$crosstool_vsn"
termcap_dir="termcap-$termcap_vsn"
zlib_dir="zlib-$zlib_vsn"
yaml_dir="yaml-$yaml_vsn"
ssl_dir="openssl-$ssl_vsn"
otp_dir="otp_src_$otp_vsn"
crosstool_tar="$crosstool_dir.tar.xz"
termcap_tar="$termcap_dir.tar.gz"
zlib_tar="$zlib_dir.tar.gz"
yaml_tar="$yaml_dir.tar.gz"
ssl_tar="$ssl_dir.tar.gz"
otp_tar="$otp_dir.tar.gz"
rel_tar="$rel_name-$rel_vsn.tar.gz"
ct_jobs=$(nproc)
src_dir="$root_dir/src"
platform='x86_64-pc-linux-gnu'
targets='x86_64-linux-gnu aarch64-linux-gnu'
build_start=$(date '+%F %T')

umask 022

#' Try to find a browser for checking dependency versions.
have_browser()
{
	for browser in 'lynx' 'links' 'elinks'
	do
		$browser -dump 'https://eturnal.net/' >'/dev/null' && return 0
	done
	return 1
}
#.

#' Check whether the given dependency version is up-to-date.
check_vsn()
{
	local name="$1"
	local our_vsn="$2"
	local src_url="$3"
	local reg_exp="$4"
	local cur_vsn=$($browser -dump "$src_url" |
	                sed -n "s/.*$reg_exp.*/\\1/p" |
	                head -1)

	if [ "$our_vsn" = "$cur_vsn" ]
	then
		return 0
	else
		error "Current $name version is: $cur_vsn"
		error "But our $name version is: $our_vsn"
		error "Update $0 or set CHECK_DEPS=false"
		exit 1
	fi
}
#.

#' Check whether our dependency versions are up-to-date.
check_deps()
{
	check_vsn 'OpenSSL' "$ssl_vsn" \
	          'https://www.openssl.org/source/' \
	          'openssl-\(1\.[0-9][0-9a-z.]*\)\.tar\.gz'
	check_vsn 'LibYAML' "$yaml_vsn" \
	          'https://pyyaml.org/wiki/LibYAML' \
	          'yaml-\([0-9][0-9.]*\)\.tar\.gz'
	check_vsn 'zlib' "$zlib_vsn" \
	          'https://zlib.net/' \
	          'zlib-\([1-9][0-9.]*\)\.tar\.gz'
	check_vsn 'Termcap' "$termcap_vsn" \
	          'https://ftp.gnu.org/gnu/termcap/' \
	          'termcap-\([1-9][0-9.]*\)\.tar\.gz'
	check_vsn 'Rebar3' "$rebar_vsn" \
	          'https://github.com/erlang/rebar3/tags' \
	          '\(3\.[0-9][0-9.]*\)\.tar\.gz'
}
#.

#' Create common part of Crosstool-NG configuration file.
create_common_config()
{
	local file="$1"

	cat >"$file" <<-'EOF'
		CT_CONFIG_VERSION="4"
		CT_DOWNLOAD_AGENT_CURL=y
		CT_OMIT_TARGET_VENDOR=y
		CT_CC_LANG_CXX=y
		CT_ARCH_64=y
		CT_KERNEL_LINUX=y
		CT_LINUX_V_3_16=y
		CT_GLIBC_V_2_19=y
		CT_GLIBC_KERNEL_VERSION_NONE=y
	EOF
}
#.

#' Create Crosstool-NG configuration file for x64.
create_x64_config()
{
	local file="$1"

	create_common_config "$file"

	cat >>"$file" <<-'EOF'
		CT_ARCH_X86=y
	EOF
}
#.

#' Create Crosstool-NG configuration file for arm64.
create_arm64_config()
{
	local file="$1"

	create_common_config "$file"

	cat >>"$file" <<-'EOF'
		CT_ARCH_ARM=y
	EOF
}
#.

#' Return our name for the given platform.
arch_name()
{
	local target="$1"

	case $target in
	x86_64*)
		printf 'x64'
		;;
	aarch64*)
		printf 'arm64'
		;;
	*)
		error "Unsupported target platform: $target"
		exit 1
		;;
	esac
}
#.

#' Return Rebar3 profile depending on compilation mode.
rebar3_profile()
{
	local mode="$1"

	if [ "$mode" = 'native' ]
	then printf 'stripped'
	else printf 'cross'
	fi
}
#.

#' Build toochain for a given target.
build_toolchain()
{
	local target="$1"
	local prefix="$2"
	local arch=$(arch_name "$target")

	if [ -d "$prefix" ]
	then
		info "Using existing toolchain in $prefix ..."
	else
		if ! [ -x "$bootstrap_dir/bin/ct-ng" ]
		then
			info "Extracting Crosstool-NG $crosstool_vsn ..."
			cd "$src_dir"
			tar -xJf "$crosstool_tar"
			cd "$OLDPWD"

			info "Building Crosstool-NG $crosstool_vsn ..."
			cd "$src_dir/$crosstool_dir"
			./configure --prefix="$bootstrap_dir"
			make
			make install
			cd "$OLDPWD"
		fi

		info "Building toolchain for $arch ..."
		cd "$root_dir"
		create_${arch}_config 'defconfig'
		ct-ng defconfig
		ct-ng build CT_PREFIX="$ct_prefix_dir" CT_JOBS="$ct_jobs"
		rm -rf 'defconfig' '.config'* '.build' 'build.log'
		cd "$OLDPWD"
	fi
}
#.

#' Build target dependencies and the actual release.
build_rel()
{
	local mode="$1"
	local target="$2"
	local prefix="$3"
	local arch="$(arch_name "$target")"
	local profile="$(rebar3_profile "$mode")"
	local rel_dir="$PWD/_build/$profile/rel/$rel_name"
	local target_src_dir="$prefix/src"
	local target_dst_dir="$prefix/$rel_name"
	local target_dst_tar="$rel_name-$rel_vsn-linux-$arch.tar.gz"
	local saved_path="$PATH"

	#
	# The "$ct_prefix_dir/$target/$target/bin" directory contains
	# cross-compilation tools without "$target-" prefix. We add it to the
	# PATH, just in case tools are called without prefix somewhere. However,
	# we try to use the prefixed tools everywhere, so it should be possible
	# to omit this directory from the path if desired. See also:
	#
	# https://stackoverflow.com/a/24243789
	#
	export PATH="$ct_prefix_dir/$target/bin:$ct_prefix_dir/$target/$target/bin:$PATH"
	export CC="$target-gcc"
	export CXX="$target-g++"
	export CPP="$target-cpp"
	export LD="$target-ld"
	export AS="$target-as"
	export AR="$target-ar"
	export NM="$target-nm"
	export RANLIB="$target-ranlib"
	export OBJCOPY="$target-objcopy"
	export STRIP="$target-strip"
	export CPPFLAGS="-I$prefix/include"
	export CFLAGS="-g0 -O2 -pipe -fomit-frame-pointer -static-libgcc $CPPFLAGS"
	export CXXFLAGS="$CFLAGS -static-libstdc++"
	export LDFLAGS="-L$prefix/lib -static-libgcc -static-libstdc++"
	export ERL_COMPILER_OPTIONS='[deterministic, no_debug_info]'

	if [ "$mode" = 'cross' ]
	then configure="./configure --host=$target --build=$platform"
	else configure='./configure'
	fi

	mkdir "$prefix"

	info 'Extracting dependencies ...'
	mkdir "$target_src_dir"
	cd "$target_src_dir"
	tar -xzf "$src_dir/$termcap_tar"
	tar -xzf "$src_dir/$zlib_tar"
	tar -xzf "$src_dir/$yaml_tar"
	tar -xzf "$src_dir/$ssl_tar"
	tar -xzf "$src_dir/$otp_tar"
	cd "$OLDPWD"

	info "Building Termcap $termcap_vsn for $arch ..."
	cd "$target_src_dir/$termcap_dir"
	$configure --prefix="$prefix"
	cat >'config.h' <<-'EOF'
		#ifndef CONFIG_H
		#define CONFIG_H
		#define INTERNAL_TERMINAL "internal:\\\n" \
			"\t:am:bs:ms:xn:xo:\\\n" \
			"\t:co#80:it#8:li#24:vt#3:\\\n" \
			"\t:@8=\\EOM:DO=\\E[%dB:K1=\\EOq:K2=\\EOr:K3=\\EOs:K4=\\EOp:K5=\\EOn:\\\n" \
			"\t:LE=\\E[%dD:RA=\\E[?7l:RI=\\E[%dC:SA=\\E[?7h:UP=\\E[%dA:\\\n" \
			"\t:ac=``aaffggjjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~:\\\n" \
			"\t:ae=^O:as=^N:bl=^G:cb=\\E[1K:cd=\\E[J:ce=\\E[K:cl=\\E[H\\E[J:\\\n" \
			"\t:cm=\\E[%i%d;%dH:cr=^M:cs=\\E[%i%d;%dr:ct=\\E[3g:do=^J:\\\n" \
			"\t:eA=\\E(B\\E)0:ho=\\E[H:k0=\\EOy:k1=\\EOP:k2=\\EOQ:k3=\\EOR:\\\n" \
			"\t:k4=\\EOS:k5=\\EOt:k6=\\EOu:k7=\\EOv:k8=\\EOl:k9=\\EOw:k;=\\EOx:\\\n" \
			"\t:kb=^H:kd=\\EOB:ke=\\E[?1l\\E>:kl=\\EOD:kr=\\EOC:ks=\\E[?1h\\E=:\\\n" \
			"\t:ku=\\EOA:le=^H:mb=\\E[5m:md=\\E[1m:me=\\E[m\\017:mr=\\E[7m:\\\n" \
			"\t:nd=\\E[C:rc=\\E8:rs=\\E>\\E[?3l\\E[?4l\\E[?5l\\E[?7h\\E[?8h:\\\n" \
			"\t:..sa=\\E[0%?%p1%p6%|%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;m%?%p9%t\\016%e\\017%;:\\\n" \
			"\t:sc=\\E7:se=\\E[m:sf=^J:so=\\E[7m:sr=\\EM:st=\\EH:ta=^I:ue=\\E[m:\\\n" \
			"\t:up=\\E[A:us=\\E[4m:"
		#endif
	EOF
	make CPPFLAGS="$CPPFLAGS -DHAVE_CONFIG_H=1"
	make install
	cd "$OLDPWD"

	info "Building zlib $zlib_vsn for $arch ..."
	cd "$target_src_dir/$zlib_dir"
	CFLAGS="$CFLAGS -O3 -fPIC" ./configure --prefix="$prefix" --static
	make
	make install
	cd "$OLDPWD"

	info "Building LibYAML $yaml_vsn for $arch ..."
	cd "$target_src_dir/$yaml_dir"
	$configure --prefix="$prefix" --disable-shared CFLAGS="$CFLAGS -fPIC"
	make
	make install
	cd "$OLDPWD"

	info "Building OpenSSL $ssl_vsn for $arch ..."
	cd "$target_src_dir/$ssl_dir"
	CFLAGS="$CFLAGS -O3 -fPIC" ./Configure no-shared no-ui-console \
	    --prefix="$prefix" \
	    --openssldir="$prefix" \
	    "linux-${target%-linux-gnu}"
	make build_libs
	make install_dev
	cd "$OLDPWD"

	info "Building Erlang/OTP $otp_vsn for $arch ..."
	if [ "$mode" = 'cross' ]
	then
		export PATH="$native_otp_bin:$PATH" # For bootstrapping/Rebar3.
		export erl_xcomp_sysroot="$prefix"
	fi
	cd "$target_src_dir/$otp_dir"
	# The additional CFLAGS/LIBS below are required by --enable-static-nifs.
	$configure \
	    --prefix="$prefix" \
	    --with-ssl="$prefix" \
	    --without-javac \
	    --disable-dynamic-ssl-lib \
	    --enable-static-nifs \
	    CFLAGS="$CFLAGS -Wl,-L$prefix/lib" \
	    LIBS='-lcrypto'
	make
	make install
	if [ "$mode" = 'native' ]
	then
		native_otp_bin="$prefix/bin"
		export PATH="$native_otp_bin:$PATH" # For Rebar3.
	else
		unset erl_xcomp_sysroot
	fi
	cd "$OLDPWD"

	info "Removing Rebar3 cache and old $rel_name builds"
	rm -rf "$HOME/.cache/rebar3" '_build'
	rebar3 clean -a

	info "Building $rel_name $rel_vsn for $arch ..."
	if [ "$mode" = 'native' ]
	then
		rebar3 as "$(rebar3_profile "$mode")" tar
	else
		ln -s "$prefix/lib" # As expected by the 'cross' profile.
		ei_inc="$prefix/lib/erlang/lib/erl_interface-"*'/include'
		ei_lib="$prefix/lib/erlang/lib/erl_interface-"*'/lib'
		LDLIBS='-lpthread' \
		    ERL_EI_INCLUDE_DIR=$(ls -1d $ei_inc) \
		    ERL_EI_LIBDIR=$(ls -1d $ei_lib) \
		    rebar3 as "$(rebar3_profile "$mode")" tar
		rm 'lib'
	fi

	info "Editing $rel_name $rel_vsn for $arch ..."
	mkdir "$target_dst_dir"
	tar -C "$target_dst_dir" -xzf "$rel_dir/$rel_tar"
	sed -i "2iexport TERM='internal'" \
	    "$target_dst_dir/bin/$rel_name" \
	    "$target_dst_dir/bin/$rel_name-$rel_vsn"
	sed -i 's/^dist_port="${ERL_DIST_PORT:-}"/dist_port="${ERL_DIST_PORT:-3470}"/' \
	    "$target_dst_dir/bin/${rel_name}ctl"
	rm "$target_dst_dir/erts-"*'/bin/epmd' # We run don't use EPMD.
	find "$target_dst_dir/lib" -type f -name 'otp_test_engine.so' \
	    -delete # Remove shared object file used only in test suite.
	find "$target_dst_dir/lib/crypto-"* "$target_dst_dir/lib/asn1-"* \
	    '(' -name 'asn1rt_nif.so' -o \
	        -name 'crypto.so' -o \
	        -name 'lib' -o \
	        -name 'priv' ')' \
	    -delete # Remove shared object files of statically linked NIFs.
	find "$target_dst_dir/lib" -type f -name '*.so' \
	    -exec "$STRIP" -s '{}' '+'
	find "$target_dst_dir/erts-"*'/bin' -type f -perm '-u+x' \
	    -exec "$STRIP" -s '{}' '+' 2>'/dev/null' || :
	test "$mode" = 'cross' &&
	    erl -noinput -eval \
	        "{ok, _} = beam_lib:strip_release('$target_dst_dir'), halt()"
	tar -C "$prefix" --owner="$rel_name" --group="$rel_name" -cf - \
	    "$rel_name" | gzip -9 >"$target_dst_tar"

	info "Created $target_dst_tar successfully."

	unset CC CXX CPP LD AS AR NM RANLIB OBJCOPY STRIP
	unset CFLAGS CXXFLAGS LDFLAGS ERL_COMPILER_OPTIONS
	export PATH="$saved_path"
}
#.

if [ "${CHECK_DEPS:-true}" = 'true' ]
then
	if have_browser
	then
		check_deps
	else
		error 'Cannot check dependency versions.'
		error 'Install a browser or set CHECK_DEPS=false'
		exit 1
	fi
else
	info "Won't check dependency versions."
fi

if ! mkdir -p "$root_dir"
then
	error 'Set BUILD_DIR to a usable build directory path.'
	exit 1
fi

# Keep existing toolchains but rebuild everything else.

info 'Removing old bootstrap tools ...'
rm -rf "$bootstrap_dir"
mkdir "$bootstrap_dir"

info 'Removing old builds ...'
rm -rf "$build_dir"
mkdir "$build_dir"

info 'Removing old source ...'
rm -rf "$src_dir"
mkdir "$src_dir"

info 'Downloading dependencies ...'
cd "$src_dir"
curl -LO "http://crosstool-ng.org/download/crosstool-ng/$crosstool_tar"
curl -LO "https://ftp.gnu.org/gnu/termcap/$termcap_tar"
curl -LO "https://zlib.net/$zlib_tar"
curl -LO "https://pyyaml.org/download/libyaml/$yaml_tar"
curl -LO "https://www.openssl.org/source/$ssl_tar"
curl -LO "https://github.com/erlang/otp/releases/download/OTP-$otp_vsn/$otp_tar"
cd "$OLDPWD"

info "Downloading Rebar3 $rebar_vsn ..."
install -d "$bootstrap_dir/bin"
cd "$bootstrap_dir/bin"
curl -LO "https://github.com/erlang/rebar3/releases/download/$rebar_vsn/rebar3"
chmod +x 'rebar3'
cd "$OLDPWD"

export PATH="$bootstrap_dir/bin:$PATH" # For Rebar3 and possibly ct-ng.

for target in $targets
do
	prefix="$build_dir/$(arch_name "$target")"
	toolchain_dir="$ct_prefix_dir/$target"

	if [ "$(uname -m)-linux-gnu" = "$target" ]
	then mode='native'
	else mode='cross'
	fi
	build_toolchain "$target" "$toolchain_dir"
	build_rel "$mode" "$target" "$prefix"
done

info "Build started: $build_start"
info "Build ended: $(date '+%F %T')"

# vim:set foldmarker=#',#. foldmethod=marker:
