version: "3.7"

services:
  eturnal:
    image: ghcr.io/processone/eturnal:latest
    hostname: eturnal
    container_name: eturnal
    restart: unless-stopped
    user: 9000:9000

    ### security options
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    ### Note: if eturnal binds to privileged ports (<1024) directly, the option "security_opt" below must be commented out.
    security_opt:
      - no-new-privileges:true
    
    ### networking options
    ports:
      - 3478:3478     # STUN/TURN non-TLS
      - 3478:3478/udp # STUN/TURN non-TLS
      # - 5349:5349   # STUN/TURN TLS
      # - 49152-65535:49152-65535/udp # TURN relay range
    # network_mode: "host"

    ### Environment variables - information on https://eturnal.net/documentation/#Environment_Variables
    # environment:
    #   - ETURNAL_RELAY_IPV4_ADDR="203.0.113.4"
    #   - ETURNAL_RELAY_IPV6_ADDR="2001:db8::4"
    #   - STUN_SERVICE="false"
    # env_file:
    #   - eturnal.env

    ### Volume mounts - Note: directories/files must be (at least) readable by the eturnal user (9000:9000)
    # volumes:
    #   - /path/to/eturnal.yml:/etc/eturnal.yml:ro # for custom config file
    #   - /path/to/tls-files:/opt/eturnal/tls      # for custom tls files
