name: 'Close stale issues'

on:
  schedule:
    - cron: '30 2 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          any-of-labels: 'awaiting-feedback'
          labels-to-remove-when-unstale: 'awaiting-feedback'
          stale-issue-label: 'stale'
          stale-issue-message: 'This issue has been open for 30 days with no activity. Remove the "stale" label or comment, otherwise the issue will be closed in 5 days.'
          close-issue-reason: 'completed'
          days-before-issue-stale: 30
          days-before-issue-close: 5
          days-before-pr-stale: -1
          days-before-pr-close: -1
