name: Container - scan latest release image

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'doc/**'
    - 'docker-k8s/examples/**'
    - 'windows/**'
    - '**.md'
  schedule:
    # Scan the image regularly (once a day)
    - cron: '44 4 * * *'

jobs:
  build:
    name: Scan current image & report results
    runs-on: "ubuntu-latest"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Extract tag of latest release
        run: |
          echo "TAG_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
      -
        name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/sando38/docker-eturnal:${{ env.TAG_VERSION }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          vuln-type: "os"
      -
        name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
