name: 'Docker: build and publish container images'

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - 'examples/**'
      - 'Formula/**'
      - 'tools/get-version'
      - 'windows/**'
      - '**.md'
  schedule:
    - cron: '22 2 */6 * *' # every 6 days to avoid gha cache being evicted
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'examples/**'
      - 'Formula/**'
      - 'tools/get-version'
      - 'windows/**'
      - '**.md'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKERHUB_REPO: eturnal/eturnal
  PKGREL_FILE: tools/ctrrel

jobs:
################################################################################
  #' check whether to compile from master branch or from tagged version
  detect-change:
    name: Check ctr version change
    runs-on: ubuntu-latest
    outputs:
      update: ${{ steps.check_version_changed.outputs.update }}
    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      -
        name: Compare ctr package-release vsn between commits
        id: check_version_changed
        run: |
          TAG_PKGREL=$(awk 'END{print}' ${{ env.PKGREL_FILE }})
          git checkout HEAD^
          TAG_PKGREL_BASELINE=$(awk 'END{print}' ${{ env.PKGREL_FILE }})
          if [ "$TAG_PKGREL" != "$TAG_PKGREL_BASELINE" ]
          then echo "update=true" >> $GITHUB_OUTPUT
          else echo "update=false" >> $GITHUB_OUTPUT
          fi

################################################################################
  #' build musl-libc based binary tarballs for x64/arm64
  build-binary-archives:
    name: ${{ matrix.config.arch }} - build ${{ matrix.config.libc }} based binary archives
    runs-on: ${{ matrix.config.runs-on }}
    strategy:
      matrix:
        config:
          - { arch: x64, runs-on: ubuntu-22.04, libc: glibc }
          - { arch: arm64, runs-on: ubuntu-22.04-arm, libc: glibc }
          - { arch: x64, runs-on: ubuntu-24.04, libc: musl }
          - { arch: arm64, runs-on: ubuntu-24.04-arm, libc: musl }
      fail-fast: false
    needs: [detect-change]
    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Install prerequisites, obtain erlang/otp version & target arch ...
        run: |
          sudo apt-get -qq update
          # https://github.com/crosstool-ng/crosstool-ng/blob/master/testing/docker/ubuntu22.04/Dockerfile
          sudo apt-get -qq install makeself build-essential \
            gcc g++ gperf bison flex texinfo help2man make libncurses5-dev \
            python3-dev autoconf automake libtool libtool-bin gawk wget bzip2 \
            xz-utils unzip patch libstdc++6 rsync git meson ninja-build \
            binfmt-support qemu-user-static
          echo "OTP_VSN=$(awk '/^otp_vsn=/ {{gsub(/[^0-9.]/, ""); print}}' tools/make-binaries)" >> $GITHUB_ENV
          echo "ARCH=$(echo ${{ matrix.config.arch }} | sed -e 's|x64|x86_64|;s|arm64|aarch64|')" >> $GITHUB_ENV
          echo "LIBC=$(echo ${{ matrix.config.libc }} | sed -e 's|glibc|gnu|')" >> $GITHUB_ENV
      -
        name: Cache toolchain directory
        uses: actions/cache@v4
        with:
          path: ~/build/
          key: ${{runner.os}}-ct-ng-1.27.0-${{ matrix.config.arch }}-${{ env.LIBC }}-${{ hashFiles('**/make-binaries') }}
          restore-keys: |
            ${{runner.os}}-ct-ng-1.27.0-${{ matrix.config.arch }}-${{ env.LIBC }}
      -
        name: On push master | extract git version
        if: needs.detect-change.outputs.update == 'false'
        run: echo "TAG_VERSION=$(echo "$(./tools/get-version)" | sed -e 's|+|-|')" >> $GITHUB_ENV
      -
        name: On release | extract release tag
        if: needs.detect-change.outputs.update == 'true'
        run: echo "TAG_VERSION=$(awk 'END{gsub("-", " "); print $1}' ${{ env.PKGREL_FILE }})" >> $GITHUB_ENV
      -
        name: On release | check out release to be published/updated
        uses: actions/checkout@v4
        if: needs.detect-change.outputs.update == 'true'
        with:
          ref: ${{ env.TAG_VERSION }}
      -
        name: Install erlang/OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VSN }}
          version-type: strict
      -
        name: Build ${{ matrix.config.arch }} ${{ env.LIBC }}-libc based binary archives
        run: CHECK_DEPS=false tools/make-binaries ${{ env.ARCH }}-linux-${{ env.LIBC }}
      -
        name: Add executables to PATH ...
        if: matrix.config.libc == 'glibc'
        run: |
          echo "$HOME/build/bootstrap/bin" >> $GITHUB_PATH
          echo "$HOME/build/eturnal/${{ env.ARCH }}-linux-${{ env.LIBC }}/bin" >> $GITHUB_PATH
      -
        name: rebar3 xref ...
        if: matrix.config.libc == 'glibc'
        run: rebar3 xref
      -
        name: rebar3 eunit ...
        if: matrix.config.libc == 'glibc'
        run: rebar3 eunit
      -
        name: rebar3 ct ...
        if: matrix.config.libc == 'glibc'
        run: rebar3 ct
      -
        name: Start container for rebar3 test suites ...
        if: matrix.config.libc == 'musl'
        run: |
          rebar3_path="$HOME/build/bootstrap/bin"
          otp_path="$HOME/build/eturnal/${{ env.ARCH }}-linux-${{ env.LIBC }}/bin"
          alpine_path='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
          arch=$(echo ${{ matrix.arch }} | sed -e 's|x64|amd64|')
          docker run --init -d --name test-suites \
                -v $HOME/build:$HOME/build \
                -v $PWD:/eturnal \
                --workdir /eturnal \
                -e PATH=$rebar3_path:$otp_path:$alpine_path \
                docker.io/alpine:latest \
                sleep 600
      - # add build-tools & git, if rebar.config uses e.g. "github" as source
        name: add build tools to the container ...
        if: matrix.config.libc == 'musl'
        run: docker exec test-suites apk add build-base git yaml-dev
      -
        name: rebar3 xref ...
        if: matrix.config.libc == 'musl'
        run: docker exec test-suites rebar3 xref
      -
        name: rebar3 eunit ...
        if: matrix.config.libc == 'musl'
        run: docker exec test-suites rebar3 eunit
      -
        name: rebar3 ct ...
        if: matrix.config.libc == 'musl'
        run: docker exec test-suites rebar3 ct
      -
        name: Stop rebar3 test container ...
        if: matrix.config.libc == 'musl'
        run: docker stop test-suites
      -
        name: Upload artifact | ${{ matrix.config.arch }} ${{ env.LIBC }}-libc based binary tarball
        uses: actions/upload-artifact@v4
        with:
          name: eturnal-${{ env.TAG_VERSION }}-linux-${{ matrix.config.libc }}-${{ matrix.config.arch }}.tar.gz
          path: eturnal-*-linux-${{ matrix.config.libc }}-${{ matrix.config.arch }}.tar.gz
          if-no-files-found: error
          retention-days: 15

# ################################################################################
#   #' build actual images for x64/arm64 with built binary tarballs
  build-ctr-binary-based:
    name: ${{ matrix.config.arch }} - ${{ matrix.config.libc }} package-based variant
    runs-on: ${{ matrix.config.runs-on }}
    strategy:
      matrix:
        config:
          - { arch: x64, runs-on: ubuntu-24.04, libc: glibc }
          - { arch: arm64, runs-on: ubuntu-24.04-arm, libc: glibc }
          - { arch: x64, runs-on: ubuntu-24.04, libc: musl }
          - { arch: arm64, runs-on: ubuntu-24.04-arm, libc: musl }
      fail-fast: false
    needs: [detect-change, build-binary-archives]
    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: On push master | extract git version
        if: needs.detect-change.outputs.update == 'false'
        run: echo "TAG_VERSION=$(echo "$(./tools/get-version)" | sed -e 's|+|-|')" >> $GITHUB_ENV
      -
        name: On release | extract release tag
        if: needs.detect-change.outputs.update == 'true'
        run: echo "TAG_VERSION=$(awk 'END{gsub("-", " "); print $1}' ${{ env.PKGREL_FILE }})" >> $GITHUB_ENV
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Extract build & environment variables
        run: |
          echo "DOCKERFILE_PATH=$(dirname $(find . -name Dockerfile))" >> $GITHUB_ENV
          echo "ARCH=$(echo ${{ matrix.config.arch }} | sed -e 's|x64|amd64|')" >> $GITHUB_ENV
          echo "LIBC=$(echo ${{ matrix.config.libc }} | sed -e 's|glibc|gnu|')" >> $GITHUB_ENV
      -
        name: Download artifact | ${{ matrix.config.arch }} ${{ env.LIBC }}-libc based binary tarball
        uses: actions/download-artifact@v4
        with:
          name: eturnal-${{ env.TAG_VERSION }}-linux-${{ matrix.config.libc }}-${{ matrix.config.arch }}.tar.gz
      -
        name: Log in to ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      -
        name: Standalone | build & push by digest
        id: build-so
        uses: docker/build-push-action@v5
        with:
          build-args: |
            METHOD=package
            LIBC=${{ matrix.config.libc }}
            VERSION=${{ env.TAG_VERSION }}
            REPOSITORY=https://github.com/${{ github.repository }}.git
            VARIANT=standalone
          context: .
          file: ${{ env.DOCKERFILE_PATH }}/Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=true
      -
        name: Simple smoke test
        run: |
          set -x
          docker run -d --name eturnal \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build-so.outputs.digest }} \
            sleep 600
          docker exec eturnal eturnalctl daemon
          docker exec eturnal eturnalctl ping
          docker exec eturnal eturnalctl info
          docker logs eturnal
          docker stop eturnal
      -
        name: Standalone | export digest | ${{ matrix.config.arch }}-${{ matrix.config.libc }}
        run: |
          mkdir -p /tmp/digests-so
          digest="${{ steps.build-so.outputs.digest }}"
          touch "/tmp/digests-so/${digest#sha256:}"
      -
        name: Standalone | upload digest | ${{ matrix.config.arch }}-${{ matrix.config.libc }}
        uses: actions/upload-artifact@v4
        with:
          name: digests-standalone-${{ matrix.config.arch }}-${{ matrix.config.libc }}
          path: /tmp/digests-so/*
          if-no-files-found: error
          retention-days: 5
      -
        name: ACME | build & push by digest
        id: build-as
        uses: docker/build-push-action@v5
        with:
          build-args: |
            METHOD=package
            LIBC=${{ matrix.config.libc }}
            VERSION=${{ env.TAG_VERSION }}
            REPOSITORY=https://github.com/${{ github.repository }}.git
            VARIANT=acme
          context: .
          file: ${{ env.DOCKERFILE_PATH }}/Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=true
      -
        name: ACME | export digest | ${{ matrix.config.arch }}-${{ matrix.config.libc }}
        run: |
          mkdir -p /tmp/digests-as
          digest="${{ steps.build-as.outputs.digest }}"
          touch "/tmp/digests-as/${digest#sha256:}"
      -
        name: ACME | upload digest | ${{ matrix.config.arch }}-${{ matrix.config.libc }}
        uses: actions/upload-artifact@v4
        with:
          name: digests-acme-${{ matrix.config.arch }}-${{ matrix.config.libc }}
          path: /tmp/digests-as/*
          if-no-files-found: error
          retention-days: 5

################################################################################
  ## merge single images to only advertise one image plus tag
  publish:
    name: ${{ matrix.registry }} - publish manifest ${{ matrix.libc }}/${{ matrix.variant }} variant
    runs-on: ubuntu-latest
    strategy:
      matrix:
        registry: [ghcr.io, docker.io]
        variant: [standalone, acme]
        libc: [glibc, musl]
      fail-fast: false
    if: github.event_name != 'pull_request' && github.event_name != 'schedule'
    needs: [detect-change, build-binary-archives, build-ctr-binary-based]
    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: On push master | extract git version and define build variants
        if: needs.detect-change.outputs.update == 'false'
        run: |
          echo "TAG_VERSION=$(echo "$(./tools/get-version)" | sed -e 's|+|-|')" >> $GITHUB_ENV
      -
        name: On release | extract release tags to be published/updated
        if: needs.detect-change.outputs.update == 'true'
        run: |
          echo "TAG_PKGREL=$(awk 'END{print}' ${{ env.PKGREL_FILE }})" >> $GITHUB_ENV
          echo "TAG_VERSION=$(awk 'END{gsub("-", " "); print $1}' ${{ env.PKGREL_FILE }})" >> $GITHUB_ENV
          echo "TAG_MINOR=$(awk 'END{gsub("\\.", " "); print $1"."$2}' ${{ env.PKGREL_FILE }})" >> $GITHUB_ENV
          echo "TAG_MAJOR=$(awk 'END{gsub("\\.", " "); print $1}' ${{ env.PKGREL_FILE }})" >> $GITHUB_ENV
      -
        name: Log in to ${{ matrix.registry }}
        uses: docker/login-action@v3
        if: |
          ( matrix.registry == 'docker.io'
            && github.repository_owner == 'processone' )
          || matrix.registry == 'ghcr.io'
        with:
          registry: ${{ matrix.registry }}
          username: ${{ (matrix.registry == 'docker.io'
                         && secrets.DOCKERHUB_USERNAME)
                     || github.repository_owner }}
          password: ${{ (matrix.registry == 'docker.io'
                         && secrets.DOCKERHUB_TOKEN)
                     || secrets.GITHUB_TOKEN }}
      -
        name: Download digests | ${{ matrix.variant }}
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-${{ matrix.variant }}-*-${{ matrix.libc }}
          merge-multiple: true
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Define tag for latest ...
        run: |
          if [ ${{ matrix.variant }} = 'standalone' ]
          then echo "TAG_LATEST=latest" >> $GITHUB_ENV
          else echo "TAG_LATEST=${{ matrix.variant }}" >> $GITHUB_ENV
          fi
      -
        name: For variant == 'acme' add a special tag suffix
        if: matrix.variant == 'acme'
        run: echo "TAG_ACME=-acme" >> $GITHUB_ENV
      -
        name: For libc == 'musl' add a special tag suffix
        if: matrix.libc == 'musl'
        run: echo "TAG_LIBC=-alpine" >> $GITHUB_ENV
      -
        name: On push master | Docker meta
        id: meta
        if: needs.detect-change.outputs.update == 'false'
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.registry }}/${{ (matrix.registry == 'docker.io'
                                        && env.DOCKERHUB_REPO)
                                        || env.IMAGE_NAME }}
          tags: |
            edge${{ env.TAG_ACME }}${{ env.TAG_LIBC }}
      -
        name: On release | Docker meta
        id: meta-rel
        if: needs.detect-change.outputs.update == 'true'
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.registry }}/${{ (matrix.registry == 'docker.io'
                                        && env.DOCKERHUB_REPO)
                                        || env.IMAGE_NAME }}
          tags: |
            ${{ env.TAG_LATEST }}${{ env.TAG_LIBC }}
            ${{ env.TAG_PKGREL }}${{ env.TAG_ACME }}${{ env.TAG_LIBC }}
            ${{ env.TAG_VERSION }}${{ env.TAG_ACME }}${{ env.TAG_LIBC }}
            ${{ env.TAG_MINOR }}${{ env.TAG_ACME }}${{ env.TAG_LIBC }}
            ${{ env.TAG_MAJOR }}${{ env.TAG_ACME }}${{ env.TAG_LIBC }}
      -
        name: Create manifest list and push
        if: |
          ( matrix.registry == 'docker.io'
            && github.repository_owner == 'processone' )
          || matrix.registry == 'ghcr.io'
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -r '"-t " + (.tags | join(" -t "))' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@sha256:%s ' *)
      -
        name: Inspect image
        if: matrix.registry == 'ghcr.io'
        run: |
          docker buildx imagetools inspect ${{ matrix.registry }}/${{ env.IMAGE_NAME }}:${{ steps.meta-rel.outputs.version }} ||
          docker buildx imagetools inspect ${{ matrix.registry }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
