name: Update DockerHub README

on:
  push:
    paths:
      - doc/CONTAINER.md
      - .github/workflows/update-dockerhub-readme.yml
env:
  README: doc/CONTAINER.md
  DOCKERHUB_REPO: eturnal/eturnal

jobs:
  dockerhub:
    name: Update DockerHub README
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Prepare ${{ env.README }}
        run: |
          sed -i 's|ghcr.io/processone/eturnal|docker.io/${{ env.DOCKERHUB_REPO }}|g' ${{ env.README }}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        if: |
          github.event_name != 'pull_request'
          && github.repository_owner == 'processone'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKERHUB_REPO }}
          readme-filepath: ./${{ env.README }}
          short-description: STUN/TURN standalone server
